import Foundation

/// Named constants for mpv [encoding commands](https://mpv.io/manual/stable/#encoding).
///
/// This file was generated by the script `other/parse_doc.rb`. Should any changes be needed to this source the
/// generator script must be updated and this source file must then be regenerated.
///
/// This source is normally regenerated when IINA updates the version of libmpv being used so that this source
/// correctly reflects the mpv client API supported by the version of the library in use.
///
/// - Attention: **DO NOT DIRECTLY MODIFY THIS GENERATED FILE FOR ANY REASON WHATSOEVER**
struct MPVEncoding: RawRepresentable {

  typealias RawValue = String

  var rawValue: RawValue

  init(_ string: String) { self.rawValue = string }

  init?(rawValue: RawValue) { self.rawValue = rawValue }

    /** --o=<filename> */
    static let o = "o"
    /** --of=<format> */
    static let of = "of"
    /** --ofopts=<options> */
    static let ofopts = "ofopts"
    /** --oac=<codec> */
    static let oac = "oac"
    /** --oacopts=<options> */
    static let oacopts = "oacopts"
    /** --ovc=<codec> */
    static let ovc = "ovc"
    /** --ovcopts=<options> */
    static let ovcopts = "ovcopts"
    /** --orawts */
    static let orawts = "orawts"
    /** --ocopy-metadata=<yes|no> */
    static let ocopyMetadata = "ocopy-metadata"
    /** --oset-metadata=<metadata-tag[ */
    static let osetMetadata = "oset-metadata"
    /** --oremove-metadata=<metadata-tag[ */
    static let oremoveMetadata = "oremove-metadata"
  }

